package com.qhit.lh.g4.perfact.t04.bean;
// Generated 2017-12-19 15:45:01 by Hibernate Tools 5.0.6.Final

import java.util.Date;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private int uid;
	private String name;
	private String password;
	private Date birthday;
	private String sex;
	private String isable;

	public TUser() {
	}

	public TUser(int uid, String name, String password, Date birthday, String sex, String isable) {
		this.uid = uid;
		this.name = name;
		this.password = password;
		this.birthday = birthday;
		this.sex = sex;
		this.isable = isable;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getIsable() {
		return this.isable;
	}

	public void setIsable(String isable) {
		this.isable = isable;
	}

}
